loyalty:
  service:
    port: 8050
    image:
      name: abdiaoo/loyaltyservice
      version: "latest"
    database:
      name: loyalties
payment:
  service:
    port: 8060
    image:
      name: abdiaoo/paymentservice
      version: "latest"
    database:
      name: payments
reservation:
  service:
    port: 8070
    image:
      name: abdiaoo/reservationservice
      version: "latest"
    database:
      name: reservations
gateway:
  service:
    port: 8080
    image:
      name: abdiaoo/gatewayservice
      version: "latest"
    isGateway: true