name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  REGISTRY: "registry.digitalocean.com/cfe-k8s-rsoi"
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to docker container registry
        run: doctl registry login
      - name: Build Images
        run: |
          docker build -f ./LoyaltyService/Dockerfile -t ${{ env.REGISTRY }}/loyalty:latest
          docker build -f ./PaymentService/Dockerfile -t ${{ env.REGISTRY }}/payment:latest
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
