name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build images
        run: |
          docker build ./LoyaltyService/ --tag cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/loyalty:latest
          docker build ./PaymentService/ --tag cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/payment:latest
          docker build ./ReservationService/ --tag cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/reservation:latest
          docker build ./Gatewayservice/ --tag cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/gateway:latest
      - name: Push images
        run: |
          docker push cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/loyalty:latest
          docker push cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/payment:latest
          docker push cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/reservation:latest
          docker push cr.yandex/${{secrets.CONTAINER_REGISTRY_ID}}/gateway:latest
      

      # TODO build, publish to docker hub, deploy to k8s

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
